name: point-cloud-pipeline
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  
  # C++ binary dependency for e57 file reading
  - xerces-c

  # 3D & Scientific Core
  - open3d
  - numpy
  - scipy

  # Interactive Notebook Visualization
  - plotly
  - ipywidgets
  - jupyterlab

  # Python Package Manager
  - pip:
    - pye57
    - -e .  # Runs editable install automatically when building the environment